edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
merge_imports = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
binop_separator = "Front"
combine_control_expr = true
struct_field_align_threshold = 20
match_block_trailing_comma = true
trailing_comma = "Vertical"
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
single_line_if_else_max_width = 50
chain_width = 60
imports_layout = "HorizontalVertical"
unstable_features = true
version = "Two"
